In [20]:
import torch
import torch.nn as nn
import pandas as pd
import numpy as np

In [3]:
train = pd.read_csv("prepared_data/train.csv")

In [4]:
grouped_and_sorted = train.groupby("uid").apply(lambda x: list(x.sort_values(by=["date"])["sid"]))

In [5]:
shuffled = grouped_and_sorted.sample(frac=1)

In [11]:
sequences = shuffled.values

In [17]:
rewards = [[1 for _ in s] for s in sequences]

In [29]:
def rolling_window(a, window):
    a = np.array(a)
    shape = a.shape[:-1] + (a.shape[-1] - window + 1, window)
    strides = a.strides + (a.strides[-1],)
    return np.lib.stride_tricks.as_strided(a, shape=shape, strides=strides)

In [40]:
sizes = [len(s) for s in sequences]

In [30]:
frame_size = 5

In [36]:
sequences_t = np.concatenate([rolling_window(i, frame_size + 1) for i in sequences], 0)

In [37]:
sequences_t.shape

(45122519, 6)

In [38]:
rewards_t = np.concatenate([rolling_window(i, frame_size + 1) for i in rewards], 0)

In [39]:
rewards_t.shape

(45122519, 6)

In [45]:
b_size = len(rewards_t)
sizes_t = torch.tensor(sizes)
done = torch.zeros(b_size)
done[torch.cumsum(sizes_t - frame_size, dim=0) - 1] = 1

In [57]:
torch.cat([torch.tensor(sequences_t[0]), torch.tensor(rewards_t[0])], 0)

tensor([ 1305, 17155, 11281,  6970,  6690, 13649,     1,     1,     1,     1,
            1,     1])

In [52]:
len(sequences[0])

35

In [53]:
done[:35]

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [82]:
class DQN(nn.Module):
    def __init__(
        self,
        action_n: int,
        embedding_dim: int,
        seq_size: int,
        ) -> None:
        super(DQN, self).__init__()
        
        self.action_embedding = nn.Embedding(action_n, embedding_dim)
        self.linears = nn.Sequential(
            nn.Linear(seq_size * embedding_dim, 128),
            nn.ReLU(),
            nn.Linear(128, 128),
            nn.ReLU(),
            nn.Linear(128, action_n)
        )

    def forward(self, state):
        x = self.action_embedding(state) # [B, S] -> [B, S, F]
        x = x.view(state.size()[0], -1) # [B, S, F] -> [B, F]
        x = self.linears(x)
        return x

In [94]:
train["sid"].min()

0

In [83]:
model = DQN(action_n=len(train["sid"].unique()), embedding_dim=32, seq_size=5)

In [87]:
state = (torch.tensor(sequences_t[0])[:-1]).unsqueeze(0)
action = (torch.tensor(sequences_t[0])[-1]).unsqueeze(0)

In [88]:
q_values = model(state)

In [91]:
q_values[0][13649]

tensor(0.0278, grad_fn=<SelectBackward0>)

In [89]:
q_values.gather(1, action.unsqueeze(1)).squeeze(1)

tensor([0.0278], grad_fn=<SqueezeBackward1>)

In [5]:
import pickle
import numpy as np

with open("prepared_data/seq_dataset.pkl", "rb") as f:
    data = pickle.load(f)

In [6]:
list(data.keys())

['train', 'validation_tr', 'validation_te', 'test_tr', 'test_te']

In [25]:
train_len = np.array([len(i) for i in data["train"]])
validation_te_len = np.array([len(i) for i in data["validation_te"]])
test_te_len = np.array([len(i) for i in data["test_te"]])

In [38]:
len(train_len)

383435

In [37]:
np.median(train_len * 0.8), np.quantile(train_len * 0.8, 0.99), (train_len * 0.8 <= 512).sum() / len(train_len)

(48.800000000000004, 615.2, 0.9822942610872768)

In [33]:
np.median(validation_te_len), np.quantile(validation_te_len, 0.99), (validation_te_len <= 128).sum() / len(validation_te_len)

(12.0, 152.0, 0.982)

In [34]:
np.median(test_te_len), np.quantile(test_te_len, 0.99), (test_te_len <= 128).sum() / len(test_te_len)

(13.0, 155.0, 0.981475)

In [35]:
len(data["validation_tr"]), len(data["validation_te"])

(40000, 40000)

In [36]:
len(data["test_tr"]), len(data["test_te"])

(40000, 40000)

In [39]:
import numpy as np
import torch

/Users/maksimshamrai/Code/rl-for-rec/venv/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [57]:
a = list(range(1, 1000))

In [58]:
a_np = np.array(a)

In [88]:
a_tt = [torch.tensor(i) for i in a]

In [63]:
%%timeit -n 100

torch.tensor(a[6:900])

54.7 µs ± 3.12 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [60]:
%%timeit -n 100

a_np[6:900]

267 ns ± 77.7 ns per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [61]:
a_t = torch.tensor(a)

In [62]:
%%timeit -n 100

a_t[6:900]

1.09 µs ± 120 ns per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [82]:
%%timeit -n 100

a_np[798]

136 ns ± 54.8 ns per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [90]:
%%timeit -n 100

a[798]

45.8 ns ± 1.93 ns per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [89]:
%%timeit -n 100

a_tt[798]

45.2 ns ± 1.98 ns per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [91]:
%%timeit -n 100

a_t[798]

1.07 µs ± 121 ns per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [53]:
%%timeit -n 100

torch.tensor(a[798])

9.59 µs ± 3.23 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [80]:
%%timeit -n 100

a[6:900]

2.07 µs ± 107 ns per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [81]:
%%timeit -n 100

a_np[6:900]

188 ns ± 12.6 ns per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [85]:
%%timeit -n 100

a_t[6:900]

1.08 µs ± 119 ns per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [87]:
%%timeit -n 100

torch.tensor(a_np[6:900])

8.62 µs ± 4.33 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [70]:
%%timeit -n 100

len(a_t)

896 ns ± 183 ns per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [71]:
%%timeit -n 100

a_t.size(0)

227 ns ± 45.7 ns per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [67]:
a_t.size(0)

999

In [101]:
%%timeit -n 100

a_t[-1]

1.08 µs ± 75.5 ns per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [104]:
%%timeit -n 100

torch.tensor(a[-1])

8.98 µs ± 5.74 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
